version: "3.8"

services:
  frontend:
    image: panupong148th/final-62070148-frontend:1.0.0
    ports:
      - "8123:80"
  backend:
    image: panupong148th/final-62070148-backend:1.0.0
    ports:
      - "8124:3330"